package nzb

import (
	"encoding/xml"
	"fmt"
	"io"
	"sort"
)

type Msg struct {
	Msgid string
	Size  int64
}

type Segment struct {
	Bytes  int64  `xml:"bytes,attr"`
	Number int    `xml:"number,attr"`
	Msgid  string `xml:",innerxml"`
}
type Nzb struct {
	File struct {
		Segments struct {
			Segment []Segment `xml:"segment"`
		} `xml:"segments"`
	} `xml:"file"`
}

func segments(msgids []Msg) string {
	// Get keys and sort
	var keys []int
	for idx, _ := range msgids {
		keys = append(keys, idx)
	}
	sort.Ints(keys)

	// <segment bytes="394827" number="1">Part1of87.CC19C709AFA241E5A8820BA44725CCE0@1444933554.local</segment>
	segments := ""
	for _, idx := range keys {
		msg := msgids[idx]
		segments += fmt.Sprintf(`<segment bytes="%d" number="%d">%s</segment>`, msg.Size, 1+idx, msg.Msgid)
	}
	return segments
}

func Build(subject string, msgids []Msg, date string) string {
	segments := segments(msgids)

	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.nzbindex.com/nzb-1.0.dtd">
<!-- NZB Generated by UF Upload -->
<nzb xmlns="http://www.newzbin.com/DTD/2003/nzb">
<file poster="support@usenet.farm" date="%s" subject="%s">
<groups>
<group>alt.binaries.test</group>
</groups>
<segments>%s</segments>
</file>
</nzb>`, date, subject, segments)
}

func Read(f io.Reader) (Nzb, error) {
	n := Nzb{}
	dec := xml.NewDecoder(f)
	if e := dec.Decode(&n); e != nil {
		return n, e
	}
	return n, nil
}
